[package]
name = "atrocy/cacher"
description = "A simple module for caching!"
version = "0.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"

[dependencies]
Signal = "sleitnick/signal@2.0.1"